### ISSUE TITLE
Cmake Error

### ISSUE THREAD

**Issue by USG-Marauder** [mangosR2/mangos#1299]
The C compiler identification is MSVC 17.0.50727.1
The CXX compiler identification is MSVC 17.0.50727.1
Check for working C compiler using: Visual Studio 11
Check for working C compiler using: Visual Studio 11 -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler using: Visual Studio 11
Check for working CXX compiler using: Visual Studio 11 -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detected 32-bit platform.
Could NOT find Git (missing:  GIT_EXECUTABLE) 

This script builds the MaNGOS server.
  Options that can be used in order to configure the process:
    PREFIX: Path where the server should be installed to
    PCH: Use precompiled headers
    DEBUG: Debug mode
  To set an option simply type -D<OPTION>=<VALUE> after 'cmake <srcs>'.
  For example: cmake .. -DDEBUG=1 -DPREFIX=/opt/mangos

MaNGOS-Core revision  : Git not found
Install server to     : C:/Program Files (x86)/MaNGOS

Use PCH               : Yes
Build in debug-mode   : No  (default)

CMake Error at C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules/ExternalProject.cmake:647 (file):
  file problem creating directory: C:/Program Files (x86)/MaNGOS
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules/ExternalProject.cmake:1657 (_ep_set_directories)
  dep/ACE_wrappers/CMakeLists.txt:39 (ExternalProject_Add)

CMake Error at C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules/ExternalProject.cmake:649 (message):
  dir 'C:/Program Files (x86)/MaNGOS' does not exist after
  file(MAKE_DIRECTORY)
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules/ExternalProject.cmake:1657 (_ep_set_directories)
  dep/ACE_wrappers/CMakeLists.txt:39 (ExternalProject_Add)

Configuring incomplete, errors occurred!

**Comment by mikev2** [comment]
I realise this is 3million years old, but google brought me here.. the answer to bogzybodo's problem for me, was to add the path to the folder containing git.exe to the user's "Path" environment variable.

In System -> Advanced system settings -> Environment variables... -> "Path" Edit... ->
Add ";C:\Program Files (x86)\Git\bin" to the end of the list.
